version: "2"
services:
  openzwave-panel:
    build:
      context: .
    image: eugenmayer/openzwave-panel
    volumes:
      - './example/options.xml:/opt/open-zwave-control-panel/config/options.xml'
    ports:
      - "8080:8080"
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"